# NumPy 

NumPy is a Linear Algebra Library for Python, the reason it is so important for Data Science with Python is that almost all of the libraries in the PyData Ecosystem rely on NumPy as one of their main building blocks.

NumPy is also incredibly fast, as it has bindings to C libraries. 

We will only learn the basics of NumPy.

## Installation Instructions

**Install NumPy and Matplotlib by going to your terminal or command prompt and typing:**
    
    conda install numpy
    conda install matplotlib

## Using NumPy

Once you've installed NumPy you can import it as a library:

In [12]:
import numpy as np
from numpy import genfromtxt
my_data = genfromtxt('my_file.csv', delimiter=',')

NumPy has many built-in functions and capabilities. We won't cover them all but instead we will focus on some of the most important aspects: vectors, arrays, matrices and number generation. Let's start by discussing arrays.

# NumPy Arrays

NumPy arrays are the main way we will use NumPy throughout the course. NumPy arrays essentially come in two flavors: vectors and matrices. Vectors are strictly 1-d arrays and matrices are 2-d (but you should note a matrix can still have only one row or one column).

Let's begin our introduction by exploring how to create NumPy arrays.

## Creating NumPy Arrays

### From a Python List

We can create an array by directly converting a list or list of lists:

In [2]:
my_list = [1,2,3]
my_list

[1, 2, 3]

In [3]:
my_vector = np.array(my_list)
print(my_vector)
print(type(my_list))
print(type(my_vector))
print(my_vector.shape)

[1 2 3]
<class 'list'>
<class 'numpy.ndarray'>
(3,)


In [4]:
my_matrix_list = [[1,2,3],[4,5,6],[7,8,9]]
print(type(my_matrix_list))

<class 'list'>


In [5]:
my_matrix = np.array(my_matrix_list)
print(type(my_matrix))
print(my_matrix.shape)
print(my_matrix)

<class 'numpy.ndarray'>
(3, 3)
[[1 2 3]
 [4 5 6]
 [7 8 9]]


## Built-in Methods

There are lots of built-in ways to generate Arrays

### arange

Return evenly spaced values within a given interval.

In [4]:
x = np.arange(0,10)
print(x)

[0 1 2 3 4 5 6 7 8 9]


In [ ]:
np.arange(0,11,2)

### zeros and ones

Generate arrays of zeros or ones

In [ ]:
np.zeros(3)

In [ ]:
np.zeros((5,5))

In [ ]:
np.ones(3)

In [ ]:
np.ones((3,3))

### linspace
Return evenly spaced numbers over a specified interval.

In [ ]:
np.linspace(0,10,3)

In [ ]:
np.linspace(0,10,50)

## eye

Creates an identity matrix

In [ ]:
np.eye(4)

## Random 

NumPy also has lots of ways to create random number arrays:

### rand
Create an array of the given shape and populate it with
random samples from a uniform distribution
over ``[0, 1)``.

In [ ]:
np.random.rand(2)

In [ ]:
np.random.rand(5,5)

### randn

Return a sample (or samples) from the "standard normal" distribution. Unlike rand which is uniform:

In [ ]:
np.random.randn(2)

In [ ]:
np.random.randn(5,5)

### randint
Return random integers from `low` (inclusive) to `high` (exclusive).

In [ ]:
np.random.randint(1,100,1)

In [ ]:
np.random.randint(1,100,10)

## Array Attributes and Methods

Let's discuss some useful attributes and methods of an array:

In [ ]:
arr = np.arange(25)
ranarr = np.random.randint(0,50,10)

In [ ]:
print(arr)

In [ ]:
print(ranarr)

## Reshape
Returns an array containing the same data with a new shape.

In [ ]:
matrix_arr = arr.reshape(5,5)

print(matrix_arr)

### max,min,argmax,argmin

These are useful methods for finding max or min values. Or to find their index locations using argmin or argmax

In [ ]:
ranarr

In [ ]:
ranarr.max()

In [ ]:
ranarr.argmax()

In [ ]:
ranarr.min()

In [ ]:
ranarr.argmin()

## Shape

Shape is an attribute that arrays have (not a method):

In [ ]:
# Vector
arr.shape
print(arr)

In [ ]:
# Notice the two sets of brackets
print(arr.reshape(1,25))

In [ ]:
arr.reshape(1,25).shape

In [ ]:
arr.reshape(25,1)

### dtype

You can also grab the data type of the object in the array:

In [ ]:
arr.dtype

# NumPy Indexing and Selection

In this lecture we will discuss how to select elements or groups of elements from an array.

In [6]:
#Creating sample array
arr = np.arange(0,11)

In [7]:
#Show
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

## Bracket Indexing and Selection
The simplest way to pick one or some elements of an array looks very similar to python lists:

In [8]:
#Get a value at an index
arr[8]

8

In [9]:
#Get values in a range
arr[1:5]

array([1, 2, 3, 4])

In [10]:
#Get values in a range
arr[:5]

array([0, 1, 2, 3, 4])

## Broadcasting

NumPy arrays differ from a normal Python list because of their ability to broadcast:

In [11]:
#Setting a value with index range (Broadcasting)
arr2 = arr
#To get a new object, you need to copy explicitly
arr_copy = arr.copy()
arr[:5]=100

#Show
print(arr)
print(arr2)
print(arr_copy)

[100 100 100 100 100   5   6   7   8   9  10]
[100 100 100 100 100   5   6   7   8   9  10]
[ 0  1  2  3  4  5  6  7  8  9 10]


## Indexing a 2D array (matrices)

The general format is **arr_2d[row][col]** or **arr_2d[row,col]**. We recommend usually using the comma notation for clarity.

In [ ]:
arr_2d = np.array([[5,10,15],[20,25,30],[35,40,45]])

#Show
arr_2d

In [ ]:
#Indexing row
arr_2d[1]

In [ ]:
# Getting individual element value
arr_2d[1,0]

In [ ]:
# 2D array slicing

#Shape (2,2) from top right corner
arr_2d[:2,1:]

## Selection

Let's briefly go over how to use brackets for selection based off of comparison operators.

In [ ]:
arr = np.arange(1,11)
arr

In [ ]:
arr > 4

In [ ]:
bool_arr = arr>4

In [ ]:
bool_arr

In [ ]:
arr[bool_arr]

In [ ]:
arr[arr>2]

# NumPy Operations

## Arithmetic

You can easily perform array with array arithmetic, or scalar with array arithmetic. Let's see some examples:

In [ ]:
arr = np.arange(0,10)

In [ ]:
arr + arr

In [ ]:
arr * arr

In [ ]:
arr - arr

In [ ]:
# Warning on division by zero, but not an error!
# Just replaced with nan
arr / arr

In [ ]:
# Also warning, but not an error instead infinity
1/arr

In [ ]:
arr**3

## Universal Array Functions

NumPy comes with many [universal array functions](http://docs.scipy.org/doc/numpy/reference/ufuncs.html), which are essentially just mathematical operations you can use to perform the operation across the array.

In [ ]:
#Taking Square Roots
np.sqrt(arr)

In [ ]:
#Calcualting exponential (e^)
np.exp(arr)

In [ ]:
np.max(arr) #same as arr.max()

In [ ]:
np.sin(arr)

# Using Matplotlib

**Plot sinus and cosinus function from -10 to 10**

In [ ]:
# Import pyplot from matplotlib
import matplotlib.pyplot as plt

In [ ]:
x = np.linspace(-10, 10, 1000)
sinus = np.sin(x)
cosinus = np.cos(x)

fig, axs = plt.subplots(2)
fig.suptitle('Plots')

axs[0].plot(x, sinus)
axs[0].set(ylabel='sinus')

axs[1].plot(x, cosinus)
axs[1].set(ylabel='cosinus')

plt.show()

# NumPy Exercises 

#### Create an array of 10 zeros 

In [ ]:
np.zeros(10)

#### Create an array of 10 ones

In [ ]:
np.ones(10)

#### Create an array of 10 fives

In [ ]:
np.ones(10)*5

#### Create an array of the integers from 10 to 50

In [ ]:
np.arange(10, 51)

# also possible: np.linspace(10,50,41, dtype=int)

#### Create an array of all the even integers from 10 to 50

In [ ]:
ten_fifty_array= np.arange(10, 51)

#Boolean Indexing
ten_fifty_array[ten_fifty_array%2 == 0]

#### Create a 3x3 matrix with values ranging from 0 to 8

In [ ]:
np.arange(9).reshape(3, 3)

#### Create a 3x3 identity matrix

In [ ]:
np.ones(9).reshape(3, 3)

#### Use NumPy to generate a random number between 0 and 1

In [ ]:
np.random.rand(1)

#### Use NumPy to generate an array of 25 random numbers sampled from a standard normal distribution

In [ ]:
np.random.randn(25)

#### Create an array of 20 linearly spaced points between 0 and 1:

In [ ]:
np.linspace(0,1,20)

## NumPy Indexing and Selection

Now you will be given a few matrices, and be asked to replicate the resulting matrix outputs using mat as input:


In [ ]:
mat = np.arange(26)[1:].reshape(5, 5)
mat

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [ ]:
mat[2:5,1:]

array([ 2,  7, 12])

In [ ]:
mat[:3,1]

array([21, 22, 23, 24, 25])

In [ ]:
mat[4]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [ ]:
mat[3:5]

### Now do the following

#### Get the sum of all the values in mat

In [ ]:
mat.sum()

#### Get the standard deviation of the values in mat

In [ ]:
np.std(mat)

#### Get the sum of all the columns in mat

In [ ]:
mat.sum(axis=0) #axis =1 returns the sum of rows

#### Consider two random arrays A and B, check if they are equal

In [ ]:
A = np.random.rand(1)
B = np.random.rand(1)
equal = A==B
print(equal)

####  Create random vector of size 10 and replace the maximum value by 0

In [ ]:
Z = np.random.rand(10)
print(Z)

Z[np.argmax(Z)] = 0
print(Z)

#### Create a 5x5 matrix with row values ranging from 0 to 4

In [ ]:
np.random.rand(5,5)*4

#### Create a random vector of size 10 and sort it

In [ ]:
Z = np.random.rand(10)
print(Z)
Z.sort()
print(Z)

**Linear algebra: Find the solution of the linear system Ax = b**

In [ ]:
# A is given as:
A = np.array([[3.0773272, 4.41689751, 1.81898491],
              [4.1242313, 1.75850224, 1.87148561],
              [2.6658522, 4.82578985, 1.95149083]])
# b is given as:
b = np.array([3.2323423, 7.32432132, 2.324132])

In [ ]:
# x = A^{-1} * b
x = np.dot(np.linalg.inv(A), b)

print(x)
# Alternative: x = np.linalg.solve(A, b)

# NumPy + Matplotlib

**Plot the functions f(x) = x², g(x) = 3x and h(x) = 1/7*exp(x) into the same plot in x = [-5, 5]. Label the axes and add a legend!!**

In [ ]:
# Import pyplot from matplotlib
import matplotlib.pyplot as plt

In [ ]:
x = np.linspace(-5, 5, 1000)

f = x**2
g = 3 * x
h = 1/7*np.exp(x)

plt.plot(x, f, label="Quadratic function")
plt.plot(x, g, label="Linear function")
plt.plot(x, h, label="Exponential function")

plt.xlabel("x")
plt.ylabel("y")

plt.grid()
plt.legend()
plt.show()

**An NPY file is a NumPy array file created by the Python software package with the NumPy library installed. It contains an array saved in the NumPy (NPY) file format. NPY files store all the information required to reconstruct an array on any computer. Let's see how to read such a file and discover what it contains!**

NPY files are opened using:

    np.load('name_of_file.npy')
    
Images are shown using:

    plt.imshow(image, cmap='gray')

In [ ]:
surprise_image_1 = np.load('surprise_image_1.npy')
surprise_image_2 = np.load('surprise_image_2.npy')

plt.figure()
plt.imshow(surprise_image_1, cmap='gray')
plt.title('Surprise Image 1')

plt.figure()
plt.imshow(surprise_image_2, cmap='gray')
plt.title('Surprise Image 2')